name: "yx某项目"
mode: dev #dev 开发模式，日志打印到控制台，prod生产模式，日志不打印控制台
port: 8080
version: V1.0.0
host: http://localhost:8080
log:
  level: info
  filename: ./logs/app.log
  max_size: 200
  max_age: 30
  max_backups: 7
datasource:
  master:
    driver_name: mysql
    host: 192.168.1.1
    user: admin
    password: 111111
    dbname: db
    port: 3306
    max_open_conns: 200
    max_idle_conns: 50
  slave:
    count: 0
    driver_name:
    hosts:
    users:
    passwords:
    dbnames:
    ports:
    max_open_conns:
    max_idle_conns:
  redis:
    host: 192.168.1.1
    port: 6379
    password: 
    db: 0
    pool_size: 100
  rabbitmq:
    enabled: true
    host: 192.168.1.1
    port: 5672
    user: aa
    password: bb
  kafka:
    enabled: true
    Addrs:  192.168.1.1:9092
  mongodb:
    enabled: true
    host: 192.168.1.1
    port: 27017
    dbname: dbname
    user: aa
    password: bb
token:
  expire_time: 30
  secret: rtcdefghijklmn1h3a84opqrstufgxyz
  issuer: af
upload_file:
  type: localhost     #上传地点 本地->localhost(集群部署需要做硬盘挂载,挂载路径需一直)  亚马逊->s3   移动云->eos  如果不填则默认本地当前目录
  domain_name: http://localhost:8080   #如果本地则填写服务器域名,其他存储桶填写对应域名
  localhost:
    public_resource_prefix: /Volumes/disk01/public/   #如果type=localhost不填则默认启动目录./file/public/
    private_resource_prefix: /Volumes/disk01/private/ #如果type=localhost不填则默认启动目录./file/private/
  s3:
    access_key_id: xxx
    Secret_access_key: xxx
    region: ca-central-1
    bucket_name: file.xx.cn